#!/bin/bash

function do_help(){
    echo "build "
}

function do_ui_build(){
    cnpm install
    npm run build 
}

for OPT in $@ ; do

    echo "开始执行： $OPT"

    case $OPT in
        build)
            do_ui_build
            ;;
        help)
            do_help
            ;;
    esac

done
